### ISSUE TITLE
Command destroyers do not contain valid attributes

### ISSUE THREAD

**Issue by M0J0144** [M0J0144/ohmu#40]
type name: Pontifex
type id: 37481

Selecting ship selects ship and returns blank attribute map (no hardpoints, hp, etc.)

**Comment by M0J0144** [comment]
Stats for these types are stored in the database as valueFloat instead of valueInt. We need to check both columns for invType attribute values.

**Comment by d0liver** [comment]
Seems to have been fixed with the new version of libdogma =)
![screenshot from 2016-06-18 13-33-05](https://cloud.githubusercontent.com/assets/6118197/16172973/49bcda80-3559-11e6-8df2-228a1b5d7a8a.png)
