### ISSUE TITLE
Module tooltips

### ISSUE THREAD

**Issue by M0J0144** [M0J0144/ohmu#45]
Create tooltips on mouse hover over modules that display basic information such as volley damage, range, etc.

**Comment by ohmutesting** [comment]
Tooltips have been successfully implemented but still need to be tested with different types of modules to ensure that appropriate relevant information is appearing

**Comment by M0J0144** [comment]
![17206bc5725d42bf991ede66d4a38b54](https://cloud.githubusercontent.com/assets/7685385/17947068/a7766556-6a10-11e6-8948-218cff2fd325.png)

**Comment by M0J0144** [comment]
libdogma does not appear to be providing the charge attributes we need to calculate missile flight range.

MaxVelocity * (ExplosionDelay / 1000)

**Comment by M0J0144** [comment]
Any missing attributes just need to be added in the AttributeMap module... Derp.
Added a bunch more stats to the tooltips including damage caused, damage resistance bonuses, energy neutralizer amount, cap bonus, armor and shield repair amounts, and a new attribute called falloff effectiveness. There are about 300 new attributes since our attribute map was created. This might be worth investigating and updating. For the time being I am adding new ones on a case by case basis.
