### ISSUE TITLE
Character login / API errors

### ISSUE THREAD

**Issue by M0J0144** [M0J0144/ohmu#46]
Logging in and redirecting to fitting tool page resulted in the following console message with item browser showing and ft-main hidden:
"SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"
Subsequently, submitting xml API alerts with:
"Couldn't connect to the server to set keys for some reason."
Had to logout to get ft-main to show up again.

**Comment by d0liver** [comment]
I'm going to close this because the whole character login system is undergoing an overhaul right now.
