### ISSUE TITLE
ShowInfo calls on charges are straight broken

### ISSUE THREAD

**Issue by M0J0144** [M0J0144/ohmu#53]
Conflagration S typeahead info event console log:
["Server outbound Message: " main.js:6
Object { request_type: "dogma", request: Object } main.js:6]

No server response. Outbound object includes type_id 12565 and 5 requested_attributes.

**Comment by ohmutesting** [comment]
pyroutes now handles info requests from typeahead allowing for stats to be retrieved from the sql db independently from dogma context
